[commit_types]
feat = { bump = "minor" }
fix = { bump = "patch" }
refactor = { bump = "patch" }
perf = { bump = "patch" }
style = { bump = "patch" }
docs = { bump = "patch" }
test = { bump = "patch" }
chore = { bump = "patch" }
ci = { bump = "patch" }
build = { bump = "patch" }
revert = { bump = "patch" }

[pre_bump_hooks]
version = "echo 'Bumping version to {{version}}'"

[post_bump_hooks]
git = "git push origin main && git push origin --tags"
